#!/bin/bash
DELAY=5
DIR=/home/nvidia/jetson-inference/build/aarch64/bin
ELF=detectnet-console
NETSPECS=(
    coco-airplane
    coco-bottle
    coco-dog
    multiped
)
PATTERNS=(
    airplane
    bottle
    dog
    peds
)
for ((i=1;i<=${#PATTERNS[@]};i++)); do
    NETSPEC=$NETSPECS[i]
    INPUT=$(ls | grep $PATTERNS[i])
    for j in $INPUT; do
        OUTPUT=~/output_$(basename $j)
        eog $j &
        cd $DIR
        ./$ELF $j $OUTPUT $NETSPEC
        cd $OLDPWD
        eog $OUTPUT &
        sleep $DELAY
    done
    rm *output*
done
