#!/bin/bash
DIR=/home/nvidia/jetson-inference/build/aarch64/bin
ELF=segnet-console
INPUT=$DIR/drone_0428.png
OUTPUT=$(pwd)/$(basename $0)_output.png
if [[ -n $1 ]]; then
	INPUT=$1
	if [[ -n $2 ]]; then
		OUTPUT=$(pwd)/$2
	fi
fi
eog $INPUT &
cd $DIR
./$ELF $INPUT $OUTPUT
cd $OLDPWD
eog $OUTPUT &
