#!/bin/bash
DIR=/home/nvidia/jetson-inference/build/aarch64/bin
ELF=detectnet-console
NETSPEC=coco-dog
INPUT=$DIR/dog_0.jpg
OUTPUT=$(pwd)/$(basename $0)_output.jpg
if [[ -n $1 ]]; then
	INPUT=$1
	if [[ -n $2 ]]; then
		OUTPUT=$(pwd)/$2
	fi
fi
eog $INPUT &
cd $DIR
./$ELF $INPUT $OUTPUT $NETSPEC
cd $OLDPWD
eog $OUTPUT &
